# Generated by Django 6.1 on 2026-08-25 23:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=100)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('photo', models.ImageField(upload_to='visitors/')),
                ('category', models.CharField(choices=[('normal', 'Normal'), ('vip', 'VIP')], default='normal', max_length=10)),
                ('badge_serial', models.CharField(max_length=20, unique=True)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('full_name',),
                'indexes': [models.Index(fields=['category'], name='visitors_vi_categor_fbd0c6_idx'), models.Index(fields=['is_active'], name='visitors_vi_is_acti_0150af_idx')],
            },
        ),
    ]
