# Generated by Django 6.1 on 2026-09-14 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0003_badge_token_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='source',
            field=models.CharField(choices=[('admin', 'Registered at the desk'), ('self', 'Self-registered')], db_index=True, default='admin', max_length=10),
        ),
    ]
