# Generated by Django 6.1 on 2026-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitors', '0004_visitor_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='source',
            field=models.CharField(choices=[('admin', 'Registered at the desk'), ('self', 'Self-registered'), ('desk', 'Registered at the walk-in desk')], db_index=True, default='admin', max_length=10),
        ),
    ]
