# Generated by Django 6.1 on 2026-08-25 23:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('scanner', 'Scanner'), ('screen', 'Screen')], max_length=10)),
                ('token_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name',),
                'indexes': [models.Index(fields=['kind', 'is_active'], name='devices_dev_kind_71b40d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=8, unique=True)),
                ('kind', models.CharField(choices=[('scanner', 'Scanner'), ('screen', 'Screen')], max_length=10)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['expires_at'], name='devices_pai_expires_19bf65_idx')],
            },
        ),
    ]
