# Generated by Django 6.1 on 2026-09-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='kind',
            field=models.CharField(choices=[('scanner', 'Scanner'), ('screen', 'Screen'), ('desk', 'Desk')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pairingcode',
            name='kind',
            field=models.CharField(choices=[('scanner', 'Scanner'), ('screen', 'Screen'), ('desk', 'Desk')], max_length=10),
        ),
    ]
