"""Three languages, and where the choice is kept.

SAME THREE AS THE REST OF VMS — English, Portuguese, Tetun — because a person
who set the dashboard to Tetun should not meet an English launcher on the same
machine. The dictionaries are generated by `scripts/generate_locales.py`; see
the note there about why they are pure ASCII.

NO GETTEXT, NO QTRANSLATOR. Qt's own translation machinery wants `.ts` sources
compiled to `.qm` by `lrelease`, which is a build step, a binary artefact and a
toolchain dependency for what is here a dictionary of 53 strings. `tr()` also
keys on the ENGLISH TEXT, so every rewording silently orphans its translations
— exactly the failure the generated table exists to make impossible.

The choice is kept in `QSettings`, which on Windows is the registry. That is
per-user and needs no writable directory beside the executable, which matters
for a PyInstaller bundle that may sit in Program Files.
"""

from __future__ import annotations

from PySide6.QtCore import QSettings

from locales.en import MESSAGES as EN
from locales.pt import MESSAGES as PT
from locales.tet import MESSAGES as TET

ORGANISATION = "VMS"
APPLICATION = "Control Center"

DICTIONARIES = {"en": EN, "pt": PT, "tet": TET}

#: Each language names itself. Somebody who has landed in a language they
#: cannot read is looking for the word they recognise, not its translation.
LANGUAGES = [
    ("en", "English"),
    ("pt", "Português"),
    ("tet", "Tetun"),
]

DEFAULT = "en"
_current = DEFAULT


def settings() -> QSettings:
    return QSettings(ORGANISATION, APPLICATION)


def load() -> str:
    """Read the remembered language, falling back rather than failing."""
    global _current
    stored = settings().value("locale", DEFAULT)
    _current = stored if stored in DICTIONARIES else DEFAULT
    return _current


def current() -> str:
    return _current


def set_locale(code: str) -> str:
    global _current
    _current = code if code in DICTIONARIES else DEFAULT
    settings().setValue("locale", _current)
    return _current


def language_name(code: str) -> str:
    for value, label in LANGUAGES:
        if value == code:
            return label
    return code


def t(key: str, **params: object) -> str:
    """Look a message up and fill its `{placeholders}`.

    A missing key returns the key itself rather than raising. This runs in a
    launcher whose whole job is to be running when something else is broken;
    taking the window down over a typo in a log line would be the wrong trade.
    The key is conspicuous enough in the UI to be found and fixed.
    """
    message = DICTIONARIES.get(_current, EN).get(key) or EN.get(key) or key
    if not params:
        return message
    try:
        return message.format(**params)
    except (KeyError, IndexError, ValueError):
        return message
