# -*- coding: utf-8 -*-
"""Emit the three dictionaries as pure-ASCII Python.

SAME RULE AS THE THREE FRONTENDS, and for the same reason. Non-ASCII is written
as \\uXXXX escapes: the first version of the dashboard's dictionaries was
written through a shell heredoc on this Windows machine and came back with the
accents mojibaked -- "Seccoes" for "Secções". It imported, it
rendered, and it was only visible by decoding the bytes. An ASCII file cannot be
transcoded by anything in the chain.

All three languages come from one table below, so a missing translation cannot
be introduced by hand, and `check()` fails the build if one is.

    ..\\..\\.venv\\Scripts\\python.exe scripts/generate_locales.py
"""
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent / "locales"

HEADER = '''"""%(title)s

GENERATED by scripts/generate_locales.py. Do not hand-edit: edit the table in
that script and re-run it. Non-ASCII is escaped on purpose -- see the note there.
"""

MESSAGES = {
'''

# (key, en, pt, tet)
M = [
    ("//", "chrome", "", ""),
    ("app.subtitle", "Visitor Management System",
     "Sistema de Gestão de Visitantes", "Sistema Jestaun Vizitante"),
    ("app.online", "ONLINE", "ONLINE", "ONLINE"),
    ("app.partial", "PARTIAL", "PARCIAL", "PARSIÁL"),
    ("app.offline", "OFFLINE", "OFFLINE", "OFFLINE"),
    ("app.runAll", "Run All", "Iniciar tudo", "Hahú hotu"),
    ("app.stopAll", "Stop All", "Parar tudo", "Para hotu"),

    ("//", "network", "", ""),
    ("net.title", "Network", "Rede", "Rede"),
    ("net.lanIp", "LAN IP", "IP da rede", "IP rede"),
    ("net.refresh", "Refresh", "Atualizar", "Atualiza"),
    ("net.refreshTip", "Re-detect the LAN address (it changes with DHCP)",
     "Voltar a detetar o endereço da rede (muda com o DHCP)",
     "Deteta fila endereçu rede (muda ho DHCP)"),
    ("net.noLan",
     "No LAN address found. Everything will work on this machine, but phones "
     "and the lobby screen will not be able to reach it.",
     "Nenhum endereço de rede encontrado. Tudo funciona nesta máquina, "
     "mas os telemóveis e o ecrã do átrio não conseguem "
     "alcançá-la.",
     "La hetan endereçu rede. Buat hotu sei funsiona iha makina ne’e, "
     "maibé telemóvel no ekrán resepsaun sei la bele to’o."),

    ("//", "services", "", ""),
    ("svc.backend", "Backend", "Servidor", "Servidór"),
    ("svc.dashboard", "Dashboard", "Painel", "Painél"),
    ("svc.screen", "Lobby Screen", "Ecrã do átrio", "Ekrán resepsaun"),
    ("svc.scanner", "Scanner", "Leitor", "Leitór"),
    ("svc.websocket", "WebSocket", "WebSocket", "WebSocket"),
    ("svc.port", "Port {port}", "Porta {port}", "Porta {port}"),
    ("svc.expoPort", "Expo — port assigned at runtime",
     "Expo — porta atribuída em execução",
     "Expo — porta fó iha momentu la’o"),
    ("svc.start", "Start", "Iniciar", "Hahú"),
    ("svc.stop", "Stop", "Parar", "Para"),
    ("svc.open", "Open", "Abrir", "Loke"),
    ("svc.starting", "Starting…", "A iniciar…", "Hahú hela…"),
    ("svc.stopping", "Stopping…", "A parar…", "Para hela…"),
    ("svc.includeInRunAll", "Include in Run All", "Incluir em Iniciar tudo",
     "Inklui iha Hahú hotu"),

    ("//", "states", "", ""),
    ("state.STOPPED", "STOPPED", "PARADO", "PARA ONA"),
    ("state.STARTING", "STARTING", "A INICIAR", "HAHÚ HELA"),
    ("state.RUNNING", "RUNNING", "A CORRER", "LA’O HELA"),
    ("state.READY", "READY", "PRONTO", "PRONTU"),
    ("state.STOPPING", "STOPPING", "A PARAR", "PARA HELA"),
    ("state.ERROR", "ERROR", "ERRO", "ERRU"),

    ("//", "logs", "", ""),
    ("log.application", "Application", "Aplicação", "Aplikasaun"),
    ("log.allOutput", "All output", "Tudo", "Saída hotu"),
    ("log.copyTab", "Copy tab", "Copiar separador", "Kopia aba"),
    ("log.clearTab", "Clear tab", "Limpar separador", "Hamoos aba"),

    ("//", "preferences", "", ""),
    ("pref.theme", "Theme", "Tema", "Tema"),
    ("pref.toDark", "Switch to dark", "Mudar para escuro", "Troka ba nakukun"),
    ("pref.toLight", "Switch to light", "Mudar para claro", "Troka ba naroman"),
    ("pref.language", "Language", "Idioma", "Lian"),

    ("//", "lifecycle messages", "", ""),
    ("msg.ready", "{app} ready. LAN address {ip}.",
     "{app} pronto. Endereço da rede {ip}.",
     "{app} prontu. Endereçu rede {ip}."),
    ("msg.runAllHint",
     "Run All checks the environment first, then starts the backend and waits "
     "for it before starting anything else.",
     "Iniciar tudo verifica primeiro o ambiente, depois inicia o servidor e "
     "espera por ele antes de iniciar o resto.",
     "Hahú hotu verifika uluk ambiente, depois hahú servidór no hein nia "
     "molok hahú buat seluk."),
    ("msg.firewall",
     "LAN access needs Windows Firewall to permit ports 8000, 3000 and 3001. "
     "No firewall rule is changed automatically.",
     "O acesso pela rede exige que a Firewall do Windows permita as portas "
     "8000, 3000 e 3001. Nenhuma regra é alterada automaticamente.",
     "Asesu liu rede presiza Firewall Windows autoriza porta 8000, 3000 no "
     "3001. Laiha regra ne’ebé muda automatikamente."),
    ("msg.lanAddress", "LAN address: {ip}", "Endereço da rede: {ip}",
     "Endereçu rede: {ip}"),
    ("msg.networkRedetected", "Network re-detected: {ip}",
     "Rede detetada de novo: {ip}", "Deteta fila rede: {ip}"),
    ("msg.alreadyRunning", "{name} is already running.",
     "{name} já está a correr.", "{name} la’o hela ona."),
    ("msg.starting", "Starting {name}…", "A iniciar {name}…",
     "Hahú {name}…"),
    ("msg.isReady", "{name} is ready.", "{name} está pronto.",
     "{name} prontu ona."),
    ("msg.scannerStarted", "{name} started. Watch its log for the QR code.",
     "{name} iniciado. Veja o registo dele para o código QR.",
     "{name} hahú ona. Haree nia rejistu ba kódigu QR."),
    ("msg.scannerDisabled", "Scanner is disabled; skipping it.",
     "O leitor está desativado; a ignorar.",
     "Leitór dezativadu; salta tiha."),
    ("msg.notReady", "Some services did not report ready. See the logs above.",
     "Alguns serviços não ficaram prontos. Veja os registos acima.",
     "Servisu balu la sai prontu. Haree rejistu iha leten."),
    ("msg.allRunning", "All services are running.",
     "Todos os serviços estão a correr.",
     "Servisu hotu la’o hela."),
    ("msg.timedOut",
     "{name} did not answer within {seconds}s. Its process may still be "
     "starting — see its log.",
     "{name} não respondeu em {seconds}s. O processo pode ainda estar a "
     "iniciar — veja o registo dele.",
     "{name} la hatán iha {seconds}s. Nia prosesu karik hahú hela — haree "
     "nia rejistu."),

    ("//", "dialogs", "", ""),
    ("dlg.cannotStart", "Cannot start VMS", "Não é possível iniciar o VMS",
     "La bele hahú VMS"),
    ("dlg.nothingStarted",
     "Nothing has been started. The Application log lists every check.",
     "Nada foi iniciado. O registo da Aplicação lista todas as "
     "verificações.",
     "Laiha buat ida hahú. Rejistu Aplikasaun hatudu verifikasaun hotu."),
    ("dlg.freePort", "Free port {port}", "Libertar a porta {port}",
     "Libera porta {port}"),
    ("dlg.freePortTitle", "Free port {port}?", "Libertar a porta {port}?",
     "Libera porta {port}?"),
    # Deliberately blunt. This launcher did not start whatever holds the port,
    # so the person clicking is the only one who can know whether it matters.
    ("dlg.freePortBody",
     "This will stop the following, and anything they started:\n\n{who}\n\n"
     "The control centre did not start them. If one of these is something "
     "else you are using, close this and stop it yourself.",
     "Isto vai parar o seguinte, e tudo o que tenha iniciado:\n\n{who}\n\n"
     "O centro de controlo não os iniciou. Se algum for outra coisa que "
     "esteja a usar, feche isto e pare-o você mesmo.",
     "Ida ne'e sei para tuir mai, no buat hotu ne'ebé sira hahú:\n\n{who}\n\n"
     "Sentru kontrolu la hahú sira. Se ida husi sira mak buat seluk ne'ebé "
     "Ita uza hela, taka ida ne'e no para rasik."),

    # Why a control is greyed out, said before it is pressed rather than by
    # nothing happening after it is. Each names the state, not the rule.
    ("app.runAllDone", "Everything is already running",
     "Ja esta tudo a correr", "Buat hotu hala'o ona"),
    ("app.runAllBusy", "Starting services...", "A iniciar servicos...",
     "Hahu servisu sira..."),
    ("app.stopAllIdle", "Nothing is running", "Nada esta a correr",
     "Laiha buat ida hala'o"),

    ("//", "development or production", "", ""),
    # The button says which mode it is IN, not which it would switch to. A
    # control that names the other state is read as a label by half the people
    # who see it, and this one decides what gets run at a conference.
    ("mode.dev", "Development", "Desenvolvimento", "Dezenvolvimentu"),
    ("mode.prod", "Production", "Producao", "Produsaun"),
    ("mode.button", "Mode: {mode}", "Modo: {mode}", "Modu: {mode}"),
    ("mode.tip",
     "Development runs the Next dev server and compiles as it serves. "
     "Production serves a build you made with `npm run build`, and starts in "
     "seconds with every page ready.",
     "Desenvolvimento executa o servidor dev do Next e compila enquanto "
     "serve. Producao serve uma compilacao feita com `npm run build`, e "
     "arranca em segundos com todas as paginas prontas.",
     "Dezenvolvimentu hala'o servidor dev Next no kompila bainhira serve. "
     "Produsaun serve build ne'ebe halo ho `npm run build`, no hahu iha "
     "segundu balun ho pajina hotu prontu."),
    ("msg.modeChanged", "Mode changed to {mode}.", "Modo alterado para {mode}.",
     "Modu muda ba {mode}."),
    ("msg.modeProdHint",
     "Production serves the last build. After editing an app, run "
     "`npm run build` in its folder, then stop and start it here.",
     "Producao serve a ultima compilacao. Depois de editar uma aplicacao, "
     "execute `npm run build` na sua pasta, depois pare e inicie-a aqui.",
     "Produsaun serve build ikus. Depois edita aplikasaun ida, hala'o "
     "`npm run build` iha ninia pasta, depois para no hahu fali iha ne'e."),
    ("dlg.modeBusy", "Stop the services first",
     "Pare primeiro os servicos", "Para uluk servisu sira"),
    ("dlg.modeBusyBody",
     "The mode decides how each service is started, so it cannot change while "
     "one is running:\n\n  {services}\n\nPress Stop All, then change the mode.",
     "O modo decide como cada servico e iniciado, por isso nao pode mudar "
     "enquanto um esta a correr:\n\n  {services}\n\nCarregue em Parar tudo e "
     "depois mude o modo.",
     "Modu deside oinsa hahu servisu ida-idak, tan ne'e la bele muda bainhira "
     "ida hala'o hela:\n\n  {services}\n\nHanehan Para hotu, depois muda modu."),
    ("dlg.notBuilt", "Not built yet", "Ainda nao compilado", "Seidauk build"),

    ("//", "freeing a port", "", ""),
    ("msg.freeingPort", "Freeing port {port}: stopping {who}.",
     "A libertar a porta {port}: a parar {who}.",
     "Libera porta {port}: para {who}."),
    ("msg.portFreed", "Port {port} is free.", "A porta {port} está livre.",
     "Porta {port} livre ona."),
    ("msg.portKillFailed", "Could not stop {who}: {reason}",
     "Não foi possível parar {who}: {reason}",
     "La bele para {who}: {reason}"),
    ("msg.portStillHeld",
     "Port {port} is still held. It may need Administrator rights, or the "
     "process may belong to another user.",
     "A porta {port} continua ocupada. Pode precisar de direitos de "
     "Administrador, ou o processo pode pertencer a outro utilizador.",
     "Porta {port} nafatin okupadu. Karik presiza direitu Administradór, ka "
     "prosesu ne'e pertense ba utilizadór seluk."),
]


def literal(text: str) -> str:
    """One message as a single-quoted, single-line, pure-ASCII Python string.

    NEWLINES ARE ESCAPED, NOT EMITTED. A message containing a real newline used
    to be written straight through into a one-line string literal, and the
    generated file then failed to import with `unterminated string literal` --
    a syntax error in a file nobody is allowed to hand-edit, blamed on the
    dictionary rather than on the generator that wrote it. Multi-line messages
    are ordinary now (a confirmation dialog listing processes), so this handles
    them rather than forbidding them.
    """
    out = []
    for ch in text:
        if ch == '"':
            out.append('\\"')
        elif ch == "\\":
            out.append("\\\\")
        elif ch == "\n":
            out.append("\\n")
        elif ch == "\r":
            out.append("\\r")
        elif ch == "\t":
            out.append("\\t")
        elif ord(ch) < 128:
            out.append(ch)
        else:
            out.append("\\u%04x" % ord(ch))
    return '"' + "".join(out) + '"'


TITLES = {
    1: "English — the source of truth for every message.",
    2: "Portuguese — European, not Brazilian. Timor-Leste follows Lisbon.",
    3: "Tetun Dili, INL orthography. Loanwords spelled the Tetun way.",
}


def build(index: int) -> str:
    lines = [HEADER % {"title": TITLES[index].encode("ascii", "backslashreplace").decode()}]
    for entry in M:
        if entry[0] == "//":
            lines.append("")
            lines.append("    # " + "-" * (60 - len(entry[1])) + " " + entry[1] + " --")
            continue
        one = '    %s: %s,' % (literal(entry[0]), literal(entry[index]))
        if len(one) <= 79:
            lines.append(one)
        else:
            lines.append("    %s:" % literal(entry[0]))
            lines.append("        %s," % literal(entry[index]))
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def check() -> None:
    keys = [e[0] for e in M if e[0] != "//"]
    assert len(keys) == len(set(keys)), "duplicate key in the table"
    for entry in M:
        if entry[0] == "//":
            continue
        for index in (1, 2, 3):
            assert entry[index].strip(), f"{entry[0]} has no translation at {index}"
        import re
        wanted = sorted(re.findall(r"\{(\w+)\}", entry[1]))
        for index in (2, 3):
            got = sorted(re.findall(r"\{(\w+)\}", entry[index]))
            assert got == wanted, f"{entry[0]}: placeholders {got} != {wanted}"


check()
ROOT.mkdir(exist_ok=True)
(ROOT / "__init__.py").write_text('"""Generated message dictionaries."""\n', encoding="utf-8")
for name, index in (("en", 1), ("pt", 2), ("tet", 3)):
    path = ROOT / f"{name}.py"
    path.write_text(build(index), encoding="utf-8")
    raw = path.read_bytes()
    bad = sum(1 for b in raw if b > 127)
    count = sum(1 for e in M if e[0] != "//")
    print(f"  {name}.py  bytes={len(raw):<6} non-ascii={bad:<3} keys={count}")
