/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Admin login
         * @description `POST /api/v1/auth/token` — admin login.
         */
        post: operations["auth_token_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/blacklist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Log out
         * @description `POST /api/v1/auth/token/blacklist` — logout.
         *
         *     Blacklisting an already-dead token still clears the cookie: a logout must not
         *     leave the browser holding something that looks like a session.
         */
        post: operations["auth_token_blacklist_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the access token
         * @description `POST /api/v1/auth/token/refresh` — rotate on the cookie.
         *
         *     `ROTATE_REFRESH_TOKENS` + `BLACKLIST_AFTER_ROTATION` mean every call issues a
         *     new refresh token and kills the old one, so the cookie is rewritten here.
         */
        post: operations["auth_token_refresh_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/badges/card": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Render a single badge PDF
         * @description Takes the raw badge token returned once by `POST /visitors` and returns a CR80 card as a PDF. The token draws the QR and is then discarded; it is never stored, and the visitor is resolved from its digest.
         *
         *     There is no GET equivalent. Only the digest is kept, so the server cannot reprint a card without being handed the token again.
         */
        post: operations["badges_card_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/badges/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue badges and export them as .xlsx with QR codes
         * @description DESTRUCTIVE. Every visitor in the file is given a NEW badge token, which invalidates the QR on any card already printed for them.
         *
         *     This is not a choice the endpoint makes: the raw token is stored nowhere, so a scannable QR can be minted but never recovered.
         *
         *     The workbook carries the QR as an image and the exact payload as text, so a card producer can re-render it at their own size. A second sheet spells out what the file is, because a spreadsheet outlives the click that made it.
         *
         *     Omit `visitor_ids` to take every visitor who has not been deleted.
         */
        post: operations["badges_export_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/badges/reissue": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue badges and return their raw tokens
         * @description DESTRUCTIVE. Every listed visitor is given a NEW badge token, which invalidates the QR on any card already printed for them.
         *
         *     Returns the raw tokens so a client can render the QR itself — on screen, or into its own layout. The server cannot return the token of an existing card, only of one it has just minted.
         *
         *     This response is the ONLY copy. Nothing stores it.
         */
        post: operations["badges_reissue_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/badges/reissue-sheet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reissue badges and render a printable PDF
         * @description DESTRUCTIVE. Every listed visitor is given a NEW badge token, which invalidates the QR on any card already printed for them, including one they are currently wearing.
         *
         *     This is not a choice the endpoint makes: the raw token exists only at the moment it is created, so reprinting is impossible and reissuing is the only thing the server can do.
         *
         *     Nine cards per A4 sheet with cut marks; more than nine paginates. A run of exactly one comes back as a single 54x85.6mm card page instead, since one card on A4 wastes the sheet.
         */
        post: operations["badges_reissue_sheet_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/badges/roster.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the visitor roster as .xlsx
         * @description Who is registered, as a spreadsheet: serial, name, country, organisation, category, badge state and registration time.
         *
         *     NON-DESTRUCTIVE. Nothing is reissued and no card stops working.
         *
         *     There is no QR column. The server stores only `sha256(token)`, so it cannot reproduce the code on a card it has already printed — see POST /badges/export for a file that has one.
         */
        get: operations["badges_roster_export_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List paired devices */
        get: operations["devices_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/{id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a device
         * @description The device's scan history stays; its token stops working.
         */
        post: operations["devices_revoke_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/pair": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Redeem a pairing code
         * @description Returns the permanent device token. It is stored only as a SHA-256 digest, so this response is the single chance to capture it.
         */
        post: operations["devices_pair_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/devices/pairing-code": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a pairing code
         * @description Short-lived, single-use. Read it off the dashboard and type it into the device standing next to you.
         */
        post: operations["devices_pairing_code_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness and identity probe
         * @description Public. Used by the scanner and the lobby screen to find the server when its address has changed. Returns the LAN address the server believes it has, which is what devices should be pointed at.
         */
        get: operations["health_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entrance log with totals
         * @description Every badge presented in the range — `valid`, `duplicate`, `revoked` and `invalid` alike. This is the security audit as well as the attendance record, so refusals are in the default view rather than behind a filter.
         *
         *     Hours are bucketed in the event's timezone, which the response names in `timezone`. Unfiltered and unpaginated: a day of a 250-visitor event is a few thousand rows on a LAN.
         */
        get: operations["reports_entries_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/entries.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the entrance log as CSV
         * @description The same filters as `/reports/entries`. Timestamps are in the event's timezone with the offset attached; visitor columns are blank for an `invalid` scan, which matched no badge.
         */
        get: operations["reports_entries_csv_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/entries.pdf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the entrance report as PDF
         * @description The same filters as `/reports/entries`, as a designed document: the headline figures, the findings in sentences, the shape of the day, then the tables. Built with ReportLab, so it renders identically wherever the server runs.
         */
        get: operations["reports_entries_pdf_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/reports/entries.xlsx": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the entrance report as .xlsx
         * @description The same filters as `/reports/entries`, as a workbook: a summary with the written findings, hourly flow with a chart, delegations, load by door, the registered visitors who never arrived, and the full log.
         *
         *     Figures are written as numbers, not text, so they can be pivoted without cleaning the file first.
         */
        get: operations["reports_entries_xlsx_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/scans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Record a badge scan
         * @description Always 200 — read `result`, not the status code. A revoked or forged badge is a business outcome (`revoked` / `invalid`), which keeps the scanner app's error handling to genuine network failures. A visitor re-presented within the dedupe window returns `duplicate`: still logged, but kept off the lobby screen.
         */
        post: operations["scans_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/screen/feed": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Backfill arrivals after a reconnect
         * @description Everything the screen missed while it was not listening.
         */
        get: operations["screen_feed_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visitors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List visitors */
        get: operations["visitors_list"];
        put?: never;
        /**
         * Register a visitor and issue a badge
         * @description Returns `badge_token`, the raw value for the QR code. It is stored only as a SHA-256 digest, so this response is the single chance to capture it — generate the badge PDF from it immediately.
         */
        post: operations["visitors_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visitors/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visitor detail, with scan history */
        get: operations["visitors_retrieve"];
        put?: never;
        post?: never;
        /** Soft-delete a visitor (also deactivates the badge) */
        delete: operations["visitors_destroy"];
        options?: never;
        head?: never;
        /** Edit a visitor */
        patch: operations["visitors_partial_update"];
        trace?: never;
    };
    "/api/v1/visitors/{id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Activate a visitor
         * @description Undo a deactivation. The badge already in the visitor's hand starts scanning again — nothing is reissued, because the token never moved.
         */
        post: operations["visitors_activate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visitors/{id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate a visitor
         * @description The visitor stays on the list and keeps their scan history; their badge stops scanning and shows `revoked` at the door. **The QR is not changed** — `activate` puts the same printed card back to work, so a lost badge that turns up again needs no reprint.
         */
        post: operations["visitors_deactivate_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/visitors/{id}/permanent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a visitor permanently
         * @description Irreversible. Drops the registration row and the visitor's photo from storage. Scans of this badge are kept and anonymised rather than deleted -- `ScanEvent.visitor` is set to null, so the entrance log still shows that something was presented at that door at that minute, and the response reports how many rows that affected. `DELETE /visitors/{id}` is the ordinary removal and is reversible by hand; this is not.
         */
        delete: operations["visitors_permanent_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Registered, with no valid scan in the period. */
        AbsentVisitor: {
            readonly badge_serial: string;
            readonly full_name: string;
            readonly country: string;
            readonly organization: string;
            readonly category: string;
        };
        /**
         * @description The auth response body.
         *
         *     Only the access token is returned. The refresh token goes out as an httpOnly
         *     cookie so no JavaScript on the dashboard can read it.
         */
        AccessToken: {
            readonly access: string;
        };
        /**
         * @description Username + password → JWT pair, for administrators only.
         *
         *     A non-staff account would receive a token that `IsAdmin` rejects on every
         *     endpoint, which reads as a broken dashboard. Failing at login instead says
         *     what actually happened.
         */
        AdminTokenObtainPairRequest: {
            username: string;
            password: string;
        };
        /**
         * @description What the registration receipt posts back to get a printable card.
         *
         *     The raw token, and only the raw token. The server resolves the visitor from
         *     its SHA-256 digest exactly as `/scans` does, so this is not an oracle: a
         *     caller who does not already hold the token gets nothing, and one who does is
         *     holding the badge anyway.
         */
        BadgeCardRequestRequest: {
            /** @description The raw badge token, as returned once by POST /visitors. Not stored; used to draw the QR and then discarded. */
            token: string;
        };
        /**
         * @description Which visitors go into the credential spreadsheet.
         *
         *     Every one of them gets a NEW token, for the same reason the sheet does: the
         *     server keeps only a digest, so a scannable QR can be minted but never
         *     recovered. Omit the list to take everyone who is still registered.
         */
        BadgeExportRequestRequest: {
            /** @description Visitors to reissue and export, in row order. Omit to export every visitor who has not been deleted. */
            visitor_ids?: string[];
        };
        /**
         * @description Which visitors to put on the sheet.
         *
         *     Every one of them gets a NEW token — see the endpoint description. There is no
         *     way to reprint an existing card, because the raw token it carries was never
         *     stored.
         */
        BadgeReissueSheetRequestRequest: {
            /** @description Visitors to reissue and print, in the order they appear on the sheet. */
            visitor_ids: string[];
        };
        CategoryCount: {
            readonly category: string;
            readonly total: number;
        };
        /**
         * @description * `normal` - Normal
         *     * `vip` - VIP
         * @enum {string}
         */
        CategoryEnum: "normal" | "vip";
        CountryCount: {
            readonly country: string;
            readonly total: number;
        };
        /** @description `token_hash` is deliberately absent — the raw token is shown once, at pairing. */
        Device: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            kind: components["schemas"]["KindEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly last_seen_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description What a device posts to `/devices/pair` — the only endpoint with no token. */
        DevicePairRequestRequest: {
            /** @description The 6-character code shown on the dashboard. */
            code: string;
            /** @description Optional label, e.g. 'North door'. Defaults to 'Scanner 2'. */
            name?: string;
        };
        /**
         * @description The pairing response — the one and only sight of the raw device token.
         *
         *     The scanner writes `token` to expo-secure-store; the screen keeps it in its
         *     local config. It cannot be recovered afterwards, only reissued by pairing again.
         */
        DevicePaired: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            kind: components["schemas"]["KindEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly last_seen_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description Permanent device token. Sent as `Authorization: Device <token>`. */
            readonly token: string;
        };
        /** @description One door's share of the traffic. */
        DoorLoad: {
            readonly device: string;
            readonly total: number;
            readonly valid: number;
            readonly refused: number;
            /** Format: double */
            readonly share: number;
        };
        /** @description One badge presentation, valid or not. */
        Entry: {
            readonly id: number;
            /** Format: date-time */
            scanned_at: string;
            result: components["schemas"]["ResultEnum"];
            /** Format: uuid */
            visitor?: string | null;
            readonly full_name: string | null;
            readonly country: string | null;
            readonly organization: string | null;
            readonly category: string | null;
            readonly badge_serial: string | null;
            readonly device_name: string;
        };
        /**
         * @description `GET /reports/entries` — the log, its totals, and what they mean.
         *
         *     `insights` carries the derived findings the PDF and the workbook print, so the
         *     dashboard renders the same conclusions rather than re-deriving them in
         *     TypeScript and quietly drifting from the exports.
         */
        EntryReport: {
            readonly timezone: string;
            /** Format: date */
            readonly date_from: string;
            /** Format: date */
            readonly date_to: string;
            readonly summary: components["schemas"]["EntrySummary"];
            readonly insights: components["schemas"]["ReportInsights"];
            readonly entries: components["schemas"]["Entry"][];
        };
        EntrySummary: {
            readonly total: number;
            readonly unique_visitors: number;
            readonly by_result: components["schemas"]["ResultCounts"];
            readonly by_hour: components["schemas"]["HourBucket"][];
            readonly by_country: components["schemas"]["CountryCount"][];
            readonly by_category: components["schemas"]["CategoryCount"][];
        };
        /** @description What a device gets back when it finds the server. */
        Health: {
            readonly service: string;
            readonly status: string;
            /** Format: date-time */
            readonly server_time: string;
            readonly lan_ip: string;
        };
        /** @description One local hour. `hour` carries its offset, so the client never guesses. */
        HourBucket: {
            /** Format: date-time */
            readonly hour: string;
            readonly total: number;
            readonly valid: number;
            readonly duplicate: number;
            readonly refused: number;
        };
        /**
         * @description * `scanner` - Scanner
         *     * `screen` - Screen
         * @enum {string}
         */
        KindEnum: "scanner" | "screen";
        PairingCode: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            kind: components["schemas"]["KindEnum"];
            /** Format: date-time */
            readonly expires_at: string;
            /** Format: date-time */
            readonly used_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        PairingCodeRequest: {
            kind: components["schemas"]["KindEnum"];
        };
        /**
         * @description `token_hash` is deliberately absent — it never leaves the database.
         *
         *     `is_active` is read-only: it is switched through `POST /visitors/{id}/activate`
         *     and `/deactivate` so each change lands in the audit log as a named action
         *     rather than as an anonymous field edit buried in a PATCH of four other
         *     fields. Neither one touches the badge token, so the printed card keeps
         *     working across the whole cycle.
         */
        PatchedVisitorRequest: {
            full_name?: string;
            country?: string;
            organization?: string;
            /** Format: binary */
            photo?: string;
            category?: components["schemas"]["CategoryEnum"];
        };
        /**
         * @description Body for refresh/blacklist.
         *
         *     Normally empty — the refresh token arrives in the `vms_refresh` cookie. The
         *     explicit field exists for non-browser clients (curl during a rehearsal).
         */
        RefreshTokenRequest: {
            refresh?: string;
        };
        ReissueResponse: {
            readonly issued: components["schemas"]["ReissuedBadge"][];
        };
        /**
         * @description One reissued badge, including the RAW token.
         *
         *     This is the same disclosure `POST /visitors` already makes, and for the same
         *     reason: the raw value exists for one moment and the caller gets the only copy.
         *     Admin-only, and the response is never cached.
         */
        ReissuedBadge: {
            /** Format: uuid */
            readonly visitor_id: string;
            readonly badge_serial: string;
            readonly full_name: string;
            readonly category: string;
            /** @description The raw badge token, exactly as the QR must encode it. Not stored; this response is the only copy. */
            readonly token: string;
        };
        /**
         * @description The derived findings — what the counts mean.
         *
         *     Served alongside the raw summary so the dashboard shows the same conclusions
         *     the PDF and the workbook print, rather than the page re-deriving them in
         *     TypeScript and quietly drifting.
         */
        ReportInsights: {
            readonly registered: number;
            readonly arrived: number;
            /** Format: double */
            readonly attendance_rate: number;
            readonly refused: number;
            /** Format: double */
            readonly refusal_rate: number;
            readonly quiet_hours: number;
            readonly not_arrived_count: number;
            /** Format: date-time */
            readonly first_arrival: string | null;
            /** Format: date-time */
            readonly last_arrival: string | null;
            /** Format: date-time */
            readonly median_arrival: string | null;
            readonly span_minutes: number;
            /** Format: date-time */
            readonly peak_hour: string | null;
            readonly peak_total: number;
            /** Format: double */
            readonly peak_share: number;
            readonly vip_arrived: number;
            /** Format: double */
            readonly vip_share: number;
            readonly repeat_people: number;
            /** Format: double */
            readonly repeat_share: number;
            readonly doors: components["schemas"]["DoorLoad"][];
            readonly not_arrived: components["schemas"]["AbsentVisitor"][];
            /** @description The findings in sentences, in the order they should be read. */
            readonly narrative: string[];
        };
        /** @description Always all four keys, zero-filled — see counts_by_result(). */
        ResultCounts: {
            readonly valid: number;
            readonly invalid: number;
            readonly revoked: number;
            readonly duplicate: number;
        };
        /**
         * @description * `valid` - Valid
         *     * `invalid` - Invalid
         *     * `revoked` - Revoked
         *     * `duplicate` - Duplicate
         * @enum {string}
         */
        ResultEnum: "valid" | "invalid" | "revoked" | "duplicate";
        /** @description The audit view of a scan — every row, including the failures. */
        ScanEvent: {
            readonly id: number;
            /** Format: uuid */
            visitor?: string | null;
            /** Format: uuid */
            device: string;
            readonly device_name: string;
            /** Format: date-time */
            scanned_at: string;
            result: components["schemas"]["ResultEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /** @description What the guard's phone posts for each badge it sees. */
        ScanRequestRequest: {
            /** @description The raw token read out of the QR code. */
            token: string;
            /**
             * Format: date-time
             * @description When the badge was presented. Sent by the device, because the offline queue may sync minutes later. Defaults to now.
             */
            scanned_at?: string;
            /**
             * Format: uuid
             * @description Identifier the device generated for this scan. Posting it twice returns the scan already recorded rather than creating a second one — the offline queue retries, and a lost response must not become a second arrival.
             */
            client_uuid?: string | null;
        };
        /**
         * @description The answer to `POST /scans` — always 200, with the verdict in `result`.
         *
         *     `visitor` is null for an `invalid` scan; a forged badge resolves to nobody.
         */
        ScanResponse: {
            readonly event_id: number;
            result: components["schemas"]["ResultEnum"];
            /** Format: date-time */
            scanned_at: string;
            readonly visitor: components["schemas"]["ScanVisitor"] | null;
        };
        /**
         * @description What the guard's phone shows: enough to match the face to the card.
         *
         *     The photo is the point. A name tells a guard who the badge claims to be; only
         *     the photo tells them whether the person holding it is that person.
         */
        ScanVisitor: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            country: string;
            organization?: string;
            category?: components["schemas"]["CategoryEnum"];
            badge_serial: string;
            /** Format: uri */
            readonly photo_url: string;
        };
        /**
         * @description What the lobby screen renders, and nothing more.
         *
         *     Sent over the WebSocket and returned by the backfill endpoint, so both paths
         *     produce identical objects and the screen can dedupe on `id`.
         */
        ScreenEvent: {
            readonly id: number;
            readonly full_name: string;
            readonly country: string;
            readonly organization: string;
            /**
             * Format: uri
             * @description Absolute, and never derived from the request — see apps/common/media.py.
             */
            readonly photo_url: string;
            readonly category: string;
            /** Format: date-time */
            scanned_at: string;
        };
        /**
         * @description `GET /screen/feed?since=` — the reconnect backfill.
         *
         *     `last_id` is the cursor to send next. It advances even when the page was
         *     truncated, so a screen that has been down for an hour catches up over
         *     several polls instead of one huge response.
         */
        ScreenFeed: {
            readonly events: components["schemas"]["ScreenEvent"][];
            readonly last_id: number;
        };
        /** @description Admin account, as the dashboard sees it. Never exposes the password hash. */
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            is_staff?: boolean;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            is_superuser?: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            is_active?: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
        };
        /**
         * @description `token_hash` is deliberately absent — it never leaves the database.
         *
         *     `is_active` is read-only: it is switched through `POST /visitors/{id}/activate`
         *     and `/deactivate` so each change lands in the audit log as a named action
         *     rather than as an anonymous field edit buried in a PATCH of four other
         *     fields. Neither one touches the badge token, so the printed card keeps
         *     working across the whole cycle.
         */
        Visitor: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            country: string;
            organization?: string;
            /** Format: uri */
            photo: string;
            category?: components["schemas"]["CategoryEnum"];
            readonly badge_serial: string;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description `GET /visitors/{id}` — the registration, its scans, and its badge token.
         *
         *     `badge_token` is here because the token is derived rather than random: the
         *     same value is on the printed card and can be recomputed at any time, so the
         *     dashboard can show a working QR for a visitor registered last week.
         *
         *     ADMIN-ONLY, AND DETAIL-ONLY. It is a working credential, so it is deliberately
         *     absent from the list endpoint — one request should not hand back 250 usable
         *     badges.
         */
        VisitorDetail: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            country: string;
            organization?: string;
            /** Format: uri */
            photo: string;
            category?: components["schemas"]["CategoryEnum"];
            readonly badge_serial: string;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            readonly scan_events: components["schemas"]["ScanEvent"][];
            /** @description Raw badge token for the QR code. Stable for the life of the badge. */
            readonly badge_token: string;
        };
        /**
         * @description The response to `POST /visitors` — the one and only sight of the raw token.
         *
         *     `badge_token` is what goes into the QR. It is not stored anywhere and cannot
         *     be recovered: the caller must print the card now (CLAUDE.md constraint #3).
         */
        VisitorIssued: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            country: string;
            organization?: string;
            /** Format: uri */
            photo: string;
            category?: components["schemas"]["CategoryEnum"];
            readonly badge_serial: string;
            readonly is_active: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
            /** @description Raw badge token for the QR code. Shown once, never again. */
            readonly badge_token: string;
        };
        /**
         * @description The response to `POST /visitors` — the one and only sight of the raw token.
         *
         *     `badge_token` is what goes into the QR. It is not stored anywhere and cannot
         *     be recovered: the caller must print the card now (CLAUDE.md constraint #3).
         */
        VisitorIssuedRequest: {
            full_name: string;
            country: string;
            organization?: string;
            /** Format: binary */
            photo: string;
            category?: components["schemas"]["CategoryEnum"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    auth_token_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminTokenObtainPairRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AdminTokenObtainPairRequest"];
                "multipart/form-data": components["schemas"]["AdminTokenObtainPairRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    auth_token_blacklist_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshTokenRequest"];
                "multipart/form-data": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            /** @description No response body */
            205: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    auth_token_refresh_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RefreshTokenRequest"];
                "multipart/form-data": components["schemas"]["RefreshTokenRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AccessToken"];
                };
            };
        };
    };
    badges_card_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BadgeCardRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BadgeCardRequestRequest"];
                "multipart/form-data": components["schemas"]["BadgeCardRequestRequest"];
            };
        };
        responses: {
            /** @description A CR80 badge PDF. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
            /** @description No visitor holds that token. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    badges_export_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["BadgeExportRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BadgeExportRequestRequest"];
                "multipart/form-data": components["schemas"]["BadgeExportRequestRequest"];
            };
        };
        responses: {
            /** @description An .xlsx workbook with one QR per visitor. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    badges_reissue_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BadgeReissueSheetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BadgeReissueSheetRequestRequest"];
                "multipart/form-data": components["schemas"]["BadgeReissueSheetRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReissueResponse"];
                };
            };
        };
    };
    badges_reissue_sheet_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BadgeReissueSheetRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["BadgeReissueSheetRequestRequest"];
                "multipart/form-data": components["schemas"]["BadgeReissueSheetRequestRequest"];
            };
        };
        responses: {
            /** @description An A4 sheet of badges as a PDF, or a single CR80 card page when exactly one visitor was requested. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    badges_roster_export_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description An .xlsx workbook. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    devices_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"][];
                };
            };
        };
    };
    devices_revoke_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this device. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Device"];
                };
            };
        };
    };
    devices_pair_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DevicePairRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["DevicePairRequestRequest"];
                "multipart/form-data": components["schemas"]["DevicePairRequestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DevicePaired"];
                };
            };
        };
    };
    devices_pairing_code_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairingCodeRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PairingCodeRequest"];
                "multipart/form-data": components["schemas"]["PairingCodeRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingCode"];
                };
            };
        };
    };
    health_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    reports_entries_retrieve: {
        parameters: {
            query?: {
                /** @description Visitor category. Also excludes `invalid` scans. */
                category?: "normal" | "vip";
                /** @description Exact country, case-insensitive. Excludes `invalid` scans, which match no visitor and so have no country. */
                country?: string;
                /** @description First day to include, inclusive. Defaults to today. */
                from?: string;
                /** @description Scan outcome. Omit to see every badge presented. */
                result?: "duplicate" | "invalid" | "revoked" | "valid";
                /** @description Last day to include, inclusive. Defaults to today. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntryReport"];
                };
            };
        };
    };
    reports_entries_csv_retrieve: {
        parameters: {
            query?: {
                /** @description Visitor category. Also excludes `invalid` scans. */
                category?: "normal" | "vip";
                /** @description Exact country, case-insensitive. Excludes `invalid` scans, which match no visitor and so have no country. */
                country?: string;
                /** @description First day to include, inclusive. Defaults to today. */
                from?: string;
                /** @description Scan outcome. Omit to see every badge presented. */
                result?: "duplicate" | "invalid" | "revoked" | "valid";
                /** @description Last day to include, inclusive. Defaults to today. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description text/csv */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    reports_entries_pdf_retrieve: {
        parameters: {
            query?: {
                /** @description Visitor category. Also excludes `invalid` scans. */
                category?: "normal" | "vip";
                /** @description Exact country, case-insensitive. Excludes `invalid` scans, which match no visitor and so have no country. */
                country?: string;
                /** @description First day to include, inclusive. Defaults to today. */
                from?: string;
                /** @description Scan outcome. Omit to see every badge presented. */
                result?: "duplicate" | "invalid" | "revoked" | "valid";
                /** @description Last day to include, inclusive. Defaults to today. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description application/pdf */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    reports_entries_xlsx_retrieve: {
        parameters: {
            query?: {
                /** @description Visitor category. Also excludes `invalid` scans. */
                category?: "normal" | "vip";
                /** @description Exact country, case-insensitive. Excludes `invalid` scans, which match no visitor and so have no country. */
                country?: string;
                /** @description First day to include, inclusive. Defaults to today. */
                from?: string;
                /** @description Scan outcome. Omit to see every badge presented. */
                result?: "duplicate" | "invalid" | "revoked" | "valid";
                /** @description Last day to include, inclusive. Defaults to today. */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description xlsx */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    scans_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScanRequestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ScanRequestRequest"];
                "multipart/form-data": components["schemas"]["ScanRequestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScanResponse"];
                };
            };
        };
    };
    screen_feed_retrieve: {
        parameters: {
            query?: {
                /** @description Last `id` the screen has already rendered. Omit or pass 0 on a cold start. */
                since?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScreenFeed"];
                };
            };
        };
    };
    visitors_list: {
        parameters: {
            query?: {
                /** @description Filter by badge category. */
                category?: "normal" | "vip";
                /** @description Exact country match, case-insensitive. */
                country?: string;
                /** @description Filter by badge state. `false` lists deactivated visitors. */
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A search term. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visitor"][];
                };
            };
        };
    };
    visitors_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["VisitorIssuedRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["VisitorIssuedRequest"];
                "application/json": components["schemas"]["VisitorIssuedRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorIssued"];
                };
            };
        };
    };
    visitors_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VisitorDetail"];
                };
            };
        };
    };
    visitors_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    visitors_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "multipart/form-data": components["schemas"]["PatchedVisitorRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedVisitorRequest"];
                "application/json": components["schemas"]["PatchedVisitorRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visitor"];
                };
            };
        };
    };
    visitors_activate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visitor"];
                };
            };
        };
    };
    visitors_deactivate_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Visitor"];
                };
            };
        };
    };
    visitors_permanent_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A UUID string identifying this visitor. */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
