/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @description * `normal` - Normal
         *     * `vip` - VIP
         * @enum {string}
         */
        CategoryEnum: "normal" | "vip";
        /** @description `token_hash` is deliberately absent — the raw token is shown once, at pairing. */
        Device: {
            /** Format: uuid */
            readonly id: string;
            name: string;
            kind: components["schemas"]["KindEnum"];
            is_active?: boolean;
            /** Format: date-time */
            readonly last_seen_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `scanner` - Scanner
         *     * `screen` - Screen
         * @enum {string}
         */
        KindEnum: "scanner" | "screen";
        PairingCode: {
            /** Format: uuid */
            readonly id: string;
            readonly code: string;
            kind: components["schemas"]["KindEnum"];
            /** Format: date-time */
            expires_at: string;
            /** Format: date-time */
            readonly used_at: string | null;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description * `valid` - Valid
         *     * `invalid` - Invalid
         *     * `revoked` - Revoked
         *     * `duplicate` - Duplicate
         * @enum {string}
         */
        ResultEnum: "valid" | "invalid" | "revoked" | "duplicate";
        /** @description The audit view of a scan — every row, including the failures. */
        ScanEvent: {
            readonly id: number;
            /** Format: uuid */
            visitor?: string | null;
            /** Format: uuid */
            device: string;
            /** Format: date-time */
            scanned_at: string;
            result: components["schemas"]["ResultEnum"];
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
        /**
         * @description What the lobby screen renders, and nothing more.
         *
         *     Sent over the WebSocket and returned by the backfill endpoint, so both paths
         *     produce identical objects and the screen can dedupe on `id`.
         */
        ScreenEvent: {
            readonly id: number;
            readonly full_name: string;
            readonly country: string;
            /** Format: uri */
            readonly photo_url: string;
            readonly category: string;
            /** Format: date-time */
            scanned_at: string;
        };
        /** @description Admin account, as the dashboard sees it. Never exposes the password hash. */
        User: {
            readonly id: number;
            /** @description Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only. */
            username: string;
            /** Email address */
            email?: string;
            first_name?: string;
            last_name?: string;
            /**
             * Staff status
             * @description Designates whether the user can log into this admin site.
             */
            is_staff?: boolean;
            /**
             * Superuser status
             * @description Designates that this user has all permissions without explicitly assigning them.
             */
            is_superuser?: boolean;
            /**
             * Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            is_active?: boolean;
            /** Format: date-time */
            readonly date_joined: string;
            /** Format: date-time */
            readonly last_login: string | null;
        };
        /** @description `token_hash` is deliberately absent — it never leaves the database. */
        Visitor: {
            /** Format: uuid */
            readonly id: string;
            full_name: string;
            country: string;
            organization?: string;
            /** Format: uri */
            photo: string;
            category?: components["schemas"]["CategoryEnum"];
            readonly badge_serial: string;
            is_active?: boolean;
            /** Format: date-time */
            readonly created_at: string;
            /** Format: date-time */
            readonly updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
