# Generated by Django 6.1 on 2026-08-25 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('visitors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('scanned_at', models.DateTimeField(db_index=True)),
                ('result', models.CharField(choices=[('valid', 'Valid'), ('invalid', 'Invalid'), ('revoked', 'Revoked'), ('duplicate', 'Duplicate')], max_length=10)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='devices.device')),
                ('visitor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scan_events', to='visitors.visitor')),
            ],
            options={
                'ordering': ('-scanned_at', '-id'),
                'indexes': [models.Index(fields=['result'], name='scans_scane_result_f908c3_idx'), models.Index(fields=['visitor', 'scanned_at'], name='scans_scane_visitor_db617d_idx')],
            },
        ),
    ]
