# Generated by Django 6.1 on 2026-08-26 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanevent',
            name='client_uuid',
            field=models.UUIDField(blank=True, null=True, unique=True),
        ),
    ]
