"""English \u2014 the source of truth for every message.

GENERATED by scripts/generate_locales.py. Do not hand-edit: edit the table in
that script and re-run it. Non-ASCII is escaped on purpose -- see the note there.
"""

MESSAGES = {


    # ------------------------------------------------------ chrome --
    "app.subtitle": "Visitor Management System",
    "app.online": "ONLINE",
    "app.partial": "PARTIAL",
    "app.offline": "OFFLINE",
    "app.runAll": "Run All",
    "app.stopAll": "Stop All",

    # ----------------------------------------------------- network --
    "net.title": "Network",
    "net.lanIp": "LAN IP",
    "net.refresh": "Refresh",
    "net.refreshTip": "Re-detect the LAN address (it changes with DHCP)",
    "net.noLan":
        "No LAN address found. Everything will work on this machine, but phones and the lobby screen will not be able to reach it.",

    # ---------------------------------------------------- services --
    "svc.backend": "Backend",
    "svc.dashboard": "Dashboard",
    "svc.screen": "Lobby Screen",
    "svc.scanner": "Scanner",
    "svc.websocket": "WebSocket",
    "svc.port": "Port {port}",
    "svc.expoPort": "Expo \u2014 port assigned at runtime",
    "svc.start": "Start",
    "svc.stop": "Stop",
    "svc.open": "Open",
    "svc.starting": "Starting\u2026",
    "svc.stopping": "Stopping\u2026",
    "svc.includeInRunAll": "Include in Run All",

    # ------------------------------------------------------ states --
    "state.STOPPED": "STOPPED",
    "state.STARTING": "STARTING",
    "state.RUNNING": "RUNNING",
    "state.READY": "READY",
    "state.STOPPING": "STOPPING",
    "state.ERROR": "ERROR",

    # -------------------------------------------------------- logs --
    "log.application": "Application",
    "log.allOutput": "All output",
    "log.copyTab": "Copy tab",
    "log.clearTab": "Clear tab",

    # ------------------------------------------------- preferences --
    "pref.theme": "Theme",
    "pref.toDark": "Switch to dark",
    "pref.toLight": "Switch to light",
    "pref.language": "Language",

    # ------------------------------------------ lifecycle messages --
    "msg.ready": "{app} ready. LAN address {ip}.",
    "msg.runAllHint":
        "Run All checks the environment first, then starts the backend and waits for it before starting anything else.",
    "msg.firewall":
        "LAN access needs Windows Firewall to permit ports 8000, 3000 and 3001. No firewall rule is changed automatically.",
    "msg.lanAddress": "LAN address: {ip}",
    "msg.networkRedetected": "Network re-detected: {ip}",
    "msg.alreadyRunning": "{name} is already running.",
    "msg.starting": "Starting {name}\u2026",
    "msg.isReady": "{name} is ready.",
    "msg.scannerStarted": "{name} started. Watch its log for the QR code.",
    "msg.scannerDisabled": "Scanner is disabled; skipping it.",
    "msg.notReady": "Some services did not report ready. See the logs above.",
    "msg.allRunning": "All services are running.",
    "msg.timedOut":
        "{name} did not answer within {seconds}s. Its process may still be starting \u2014 see its log.",

    # ----------------------------------------------------- dialogs --
    "dlg.cannotStart": "Cannot start VMS",
    "dlg.nothingStarted":
        "Nothing has been started. The Application log lists every check.",
}
