"""Portuguese \u2014 European, not Brazilian. Timor-Leste follows Lisbon.

GENERATED by scripts/generate_locales.py. Do not hand-edit: edit the table in
that script and re-run it. Non-ASCII is escaped on purpose -- see the note there.
"""

MESSAGES = {


    # ------------------------------------------------------ chrome --
    "app.subtitle": "Sistema de Gest\u00e3o de Visitantes",
    "app.online": "ONLINE",
    "app.partial": "PARCIAL",
    "app.offline": "OFFLINE",
    "app.runAll": "Iniciar tudo",
    "app.stopAll": "Parar tudo",

    # ----------------------------------------------------- network --
    "net.title": "Rede",
    "net.lanIp": "IP da rede",
    "net.refresh": "Atualizar",
    "net.refreshTip":
        "Voltar a detetar o endere\u00e7o da rede (muda com o DHCP)",
    "net.noLan":
        "Nenhum endere\u00e7o de rede encontrado. Tudo funciona nesta m\u00e1quina, mas os telem\u00f3veis e o ecr\u00e3 do \u00e1trio n\u00e3o conseguem alcan\u00e7\u00e1-la.",

    # ---------------------------------------------------- services --
    "svc.backend": "Servidor",
    "svc.dashboard": "Painel",
    "svc.screen": "Ecr\u00e3 do \u00e1trio",
    "svc.scanner": "Leitor",
    "svc.websocket": "WebSocket",
    "svc.port": "Porta {port}",
    "svc.expoPort": "Expo \u2014 porta atribu\u00edda em execu\u00e7\u00e3o",
    "svc.start": "Iniciar",
    "svc.stop": "Parar",
    "svc.open": "Abrir",
    "svc.starting": "A iniciar\u2026",
    "svc.stopping": "A parar\u2026",
    "svc.includeInRunAll": "Incluir em Iniciar tudo",

    # ------------------------------------------------------ states --
    "state.STOPPED": "PARADO",
    "state.STARTING": "A INICIAR",
    "state.RUNNING": "A CORRER",
    "state.READY": "PRONTO",
    "state.STOPPING": "A PARAR",
    "state.ERROR": "ERRO",

    # -------------------------------------------------------- logs --
    "log.application": "Aplica\u00e7\u00e3o",
    "log.allOutput": "Tudo",
    "log.copyTab": "Copiar separador",
    "log.clearTab": "Limpar separador",

    # ------------------------------------------------- preferences --
    "pref.theme": "Tema",
    "pref.toDark": "Mudar para escuro",
    "pref.toLight": "Mudar para claro",
    "pref.language": "Idioma",

    # ------------------------------------------ lifecycle messages --
    "msg.ready": "{app} pronto. Endere\u00e7o da rede {ip}.",
    "msg.runAllHint":
        "Iniciar tudo verifica primeiro o ambiente, depois inicia o servidor e espera por ele antes de iniciar o resto.",
    "msg.firewall":
        "O acesso pela rede exige que a Firewall do Windows permita as portas 8000, 3000 e 3001. Nenhuma regra \u00e9 alterada automaticamente.",
    "msg.lanAddress": "Endere\u00e7o da rede: {ip}",
    "msg.networkRedetected": "Rede detetada de novo: {ip}",
    "msg.alreadyRunning": "{name} j\u00e1 est\u00e1 a correr.",
    "msg.starting": "A iniciar {name}\u2026",
    "msg.isReady": "{name} est\u00e1 pronto.",
    "msg.scannerStarted":
        "{name} iniciado. Veja o registo dele para o c\u00f3digo QR.",
    "msg.scannerDisabled": "O leitor est\u00e1 desativado; a ignorar.",
    "msg.notReady":
        "Alguns servi\u00e7os n\u00e3o ficaram prontos. Veja os registos acima.",
    "msg.allRunning": "Todos os servi\u00e7os est\u00e3o a correr.",
    "msg.timedOut":
        "{name} n\u00e3o respondeu em {seconds}s. O processo pode ainda estar a iniciar \u2014 veja o registo dele.",

    # ----------------------------------------------------- dialogs --
    "dlg.cannotStart": "N\u00e3o \u00e9 poss\u00edvel iniciar o VMS",
    "dlg.nothingStarted":
        "Nada foi iniciado. O registo da Aplica\u00e7\u00e3o lista todas as verifica\u00e7\u00f5es.",
    "dlg.freePort": "Libertar a porta {port}",
    "dlg.freePortTitle": "Libertar a porta {port}?",
    "dlg.freePortBody":
        "Isto vai parar o seguinte, e tudo o que tenha iniciado:\n\n{who}\n\nO centro de controlo n\u00e3o os iniciou. Se algum for outra coisa que esteja a usar, feche isto e pare-o voc\u00ea mesmo.",

    # ----------------------------------- development or production --
    "mode.dev": "Desenvolvimento",
    "mode.prod": "Producao",
    "mode.button": "Modo: {mode}",
    "mode.tip":
        "Desenvolvimento executa o servidor dev do Next e compila enquanto serve. Producao serve uma compilacao feita com `npm run build`, e arranca em segundos com todas as paginas prontas.",
    "msg.modeChanged": "Modo alterado para {mode}.",
    "msg.modeProdHint":
        "Producao serve a ultima compilacao. Depois de editar uma aplicacao, execute `npm run build` na sua pasta, depois pare e inicie-a aqui.",
    "dlg.modeBusy": "Pare primeiro os servicos",
    "dlg.modeBusyBody":
        "O modo decide como cada servico e iniciado, por isso nao pode mudar enquanto um esta a correr:\n\n  {services}\n\nCarregue em Parar tudo e depois mude o modo.",
    "dlg.notBuilt": "Ainda nao compilado",

    # ---------------------------------------------- freeing a port --
    "msg.freeingPort": "A libertar a porta {port}: a parar {who}.",
    "msg.portFreed": "A porta {port} est\u00e1 livre.",
    "msg.portKillFailed": "N\u00e3o foi poss\u00edvel parar {who}: {reason}",
    "msg.portStillHeld":
        "A porta {port} continua ocupada. Pode precisar de direitos de Administrador, ou o processo pode pertencer a outro utilizador.",
}
