"""Tetun Dili, INL orthography. Loanwords spelled the Tetun way.

GENERATED by scripts/generate_locales.py. Do not hand-edit: edit the table in
that script and re-run it. Non-ASCII is escaped on purpose -- see the note there.
"""

MESSAGES = {


    # ------------------------------------------------------ chrome --
    "app.subtitle": "Sistema Jestaun Vizitante",
    "app.online": "ONLINE",
    "app.partial": "PARSI\u00c1L",
    "app.offline": "OFFLINE",
    "app.runAll": "Hah\u00fa hotu",
    "app.stopAll": "Para hotu",

    # ----------------------------------------------------- network --
    "net.title": "Rede",
    "net.lanIp": "IP rede",
    "net.refresh": "Atualiza",
    "net.refreshTip": "Deteta fila endere\u00e7u rede (muda ho DHCP)",
    "net.noLan":
        "La hetan endere\u00e7u rede. Buat hotu sei funsiona iha makina ne\u2019e, maib\u00e9 telem\u00f3vel no ekr\u00e1n resepsaun sei la bele to\u2019o.",

    # ---------------------------------------------------- services --
    "svc.backend": "Servid\u00f3r",
    "svc.dashboard": "Pain\u00e9l",
    "svc.screen": "Ekr\u00e1n resepsaun",
    "svc.scanner": "Leit\u00f3r",
    "svc.websocket": "WebSocket",
    "svc.port": "Porta {port}",
    "svc.expoPort": "Expo \u2014 porta f\u00f3 iha momentu la\u2019o",
    "svc.start": "Hah\u00fa",
    "svc.stop": "Para",
    "svc.open": "Loke",
    "svc.starting": "Hah\u00fa hela\u2026",
    "svc.stopping": "Para hela\u2026",
    "svc.includeInRunAll": "Inklui iha Hah\u00fa hotu",

    # ------------------------------------------------------ states --
    "state.STOPPED": "PARA ONA",
    "state.STARTING": "HAH\u00da HELA",
    "state.RUNNING": "LA\u2019O HELA",
    "state.READY": "PRONTU",
    "state.STOPPING": "PARA HELA",
    "state.ERROR": "ERRU",

    # -------------------------------------------------------- logs --
    "log.application": "Aplikasaun",
    "log.allOutput": "Sa\u00edda hotu",
    "log.copyTab": "Kopia aba",
    "log.clearTab": "Hamoos aba",

    # ------------------------------------------------- preferences --
    "pref.theme": "Tema",
    "pref.toDark": "Troka ba nakukun",
    "pref.toLight": "Troka ba naroman",
    "pref.language": "Lian",

    # ------------------------------------------ lifecycle messages --
    "msg.ready": "{app} prontu. Endere\u00e7u rede {ip}.",
    "msg.runAllHint":
        "Hah\u00fa hotu verifika uluk ambiente, depois hah\u00fa servid\u00f3r no hein nia molok hah\u00fa buat seluk.",
    "msg.firewall":
        "Asesu liu rede presiza Firewall Windows autoriza porta 8000, 3000 no 3001. Laiha regra ne\u2019eb\u00e9 muda automatikamente.",
    "msg.lanAddress": "Endere\u00e7u rede: {ip}",
    "msg.networkRedetected": "Deteta fila rede: {ip}",
    "msg.alreadyRunning": "{name} la\u2019o hela ona.",
    "msg.starting": "Hah\u00fa {name}\u2026",
    "msg.isReady": "{name} prontu ona.",
    "msg.scannerStarted":
        "{name} hah\u00fa ona. Haree nia rejistu ba k\u00f3digu QR.",
    "msg.scannerDisabled": "Leit\u00f3r dezativadu; salta tiha.",
    "msg.notReady": "Servisu balu la sai prontu. Haree rejistu iha leten.",
    "msg.allRunning": "Servisu hotu la\u2019o hela.",
    "msg.timedOut":
        "{name} la hat\u00e1n iha {seconds}s. Nia prosesu karik hah\u00fa hela \u2014 haree nia rejistu.",

    # ----------------------------------------------------- dialogs --
    "dlg.cannotStart": "La bele hah\u00fa VMS",
    "dlg.nothingStarted":
        "Laiha buat ida hah\u00fa. Rejistu Aplikasaun hatudu verifikasaun hotu.",
    "dlg.freePort": "Libera porta {port}",
    "dlg.freePortTitle": "Libera porta {port}?",
    "dlg.freePortBody":
        "Ida ne'e sei para tuir mai, no buat hotu ne'eb\u00e9 sira hah\u00fa:\n\n{who}\n\nSentru kontrolu la hah\u00fa sira. Se ida husi sira mak buat seluk ne'eb\u00e9 Ita uza hela, taka ida ne'e no para rasik.",

    # ---------------------------------------------- freeing a port --
    "msg.freeingPort": "Libera porta {port}: para {who}.",
    "msg.portFreed": "Porta {port} livre ona.",
    "msg.portKillFailed": "La bele para {who}: {reason}",
    "msg.portStillHeld":
        "Porta {port} nafatin okupadu. Karik presiza direitu Administrad\u00f3r, ka prosesu ne'e pertense ba utilizad\u00f3r seluk.",
}
